### PR TITLE
fix launch file name for tiago_nav_bringup

### PR DESCRIPTION
**Pull request by david-wb**
Addresses #34

### CODE REVIEW

**Comment by Noel215** [comment]
Hi @david-wb,

I see some extra changes in this PR, could you update it only with the renaming?
Probably you will need to rebase your local repository.

Thanks for the PR!

**Comment by david-wb** [comment]
@Noel215 It's updated but you may want to squash these commits.

**Comment by kavikode** [comment]
How can we pull this request in the terminal because I am new to the VCS imports?

**Comment by Noel215** [comment]
Thanks for the PR!

**Comment by Noel215** [comment]
@kavikode now that this is merged you can use `vcs pull` to get the latest changes.

**Pull request merged**
